### ISSUE TITLE
Possible to set rotate_every to datetime parameter?

### ISSUE THREAD

**Issue by isaachinman** [Coggle/s3-streamlogger#10]
Not sure if anyone maintains this repository, but I am wondering if it is possible to set the `rotate_every` in such a way that there will be one file per calendar day, regardless of the specific time when the process is started or restarted.

I have integrated this streamlogger into a production application, which restarts semi-frequently with deployments at irregular times. Having `rotate_every` be an arbitrary interval of seconds after the last deployment (process restart) is a bit weird.

I'll take a look through the source, and if I can't find something suitable will probably fork this and pull in momentjs as a dep.

**Comment by isaachinman** [comment]
**Update:** fork created - [s3-streamlogger-daily](https://github.com/isaachinman/s3-streamlogger-daily). Also available on [npm](https://www.npmjs.com/package/s3-streamlogger-daily).

If the maintainer of this repo wants to merge the fork (no breaking changes), let me know. I am going to have to keep my fork open regardless due to personal use reasons.

**Comment by autopulated** [comment]
Hi! Thanks for the suggestion – this repository is maintained (we use it in production at Coggle)

The file rotation accomplishes two things: it makes sure that the file doesn't grow too big (enforced by the `buffer_size`) parameter (if the file gets too big, the data transfer costs increase), and that when you're reviewing the log files (for example with https://github.com/Coggle/tails3), you don't need to download the data from a wide time period when you're only interested in a narrow time period.

The other side of that trade-off is that file rotation adds a small cost for additional requests.

In production we rotate files at least once an hour – but most often they are rotated sooner than that due to the buffering limit.

I can see the attraction of having files rotated at fixed intervals, so the filenames are more predictable, but as they might be rotated at any time by the `buffer_size` limit, this isn't possible to achieve. Instead that's why we wrote the tails3 tool, which can automatically pull and re-assemble the right files for a specific time range.

**Comment by isaachinman** [comment]
Sure, but when you have services spread across timezones it starts to make a lot less sense. Anyways, "too big" is subjective and `buffer_size` is adjustable... In my specific case, I would prefer to allow a logfile to increase in size without limit, and have predictable filenames based on calendar days.

Anyways, the fork is there for anyone who has similar desires. I appreciate this repo, cheers!

**Comment by autopulated** [comment]
Thanks for explaining – I'm not necessarily against supporting daily/etc rotations, just warning that there will always be some case where the file name could be different to the expected one.

One other thing I forgot to mention is that if you have a service logging to a particular filename, restart it, and then continue logging to the same file name, the data in the file will be overwritten. (S3 does not support appending to files: the entire buffer is uploaded each time).

(That's actually the reason the name format was changed to include seconds instead of just minutes: a service restarting within a minute of starting would overwrite its log file.)

**Comment by isaachinman** [comment]
Yes, your second paragraph is the more important part to me, and something I realised immediately.

But, I'm not sure you're totally right. S3 does support multi-part file uploads and I think that'd be the way around it... the fork I created is good enough for my current use case but I do plan on figuring out multi-part uploads so that restarts, or even multiple services running in parallel, would all write to the same file.

But I think you know more about this than I, so feel free to correct me.

**Comment by autopulated** [comment]
Multi-part upload support would be awesome if you can make it work! I don't think support is quite there in s3 though:
If the process is terminated or connection lost during a multi-part upload, you don't get a file in s3, but a leftover multi-part upload that needs either completing or aborting. To continue a multi-part upload you also need to know the index of the chunk to continue from, which would require persisting that locally somewhere.
Also the part-size is 5MB, so I don't think anything could be uploaded until 5MB of data had been accumulated (or I suppose smaller files than that could be overwritten, or downloaded and then re-written).

So yeah, it seems complicated, but if there's a solution to make it work though that would be great!

**Comment by isaachinman** [comment]
Sure, multi-part upload is probably the "best" way to do it, but also probably the most complicated.

A much simpler way (wouldn't support parallel processes) would be to simply check for the existence of the object key in the specified path, and add it to memory if it exists.

**Comment by autopulated** [comment]
Yup that along with "day" support I would definitely be OK with merging.

**Comment by isaachinman** [comment]
Okay, I'll look into it.

**Comment by isaachinman** [comment]
@autopulated Take a look at [this](https://github.com/isaachinman/s3-streamlogger-daily/commit/f16eb9e814b541ec2cd15e5707308c2ee85e46a5) when you get a chance.

It's quick work (quite busy today), but that's the general idea for the "simple" version of writing to an existing file.
